version: '3'
services:
  tradeshift-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
    ports:
      - 8080:8080
    links:
      - postgres
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres_pwd
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
